In [7]:
import math
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [8]:
penguins_adelie = pd.read_csv("https://raw.githubusercontent.com/bu-cds-omds/dx602-examples/refs/heads/main/data/palmer-penguins-adelie.csv", index_col="Sample Number")
penguins_gentoo = pd.read_csv("https://raw.githubusercontent.com/bu-cds-omds/dx602-examples/refs/heads/main/data/palmer-penguins-gentoo.csv", index_col="Sample Number")
penguins_chinstrap = pd.read_csv("https://raw.githubusercontent.com/bu-cds-omds/dx602-examples/refs/heads/main/data/palmer-penguins-chinstrap.csv", index_col="Sample Number")
penguins = pd.concat([penguins_adelie, penguins_gentoo, penguins_chinstrap])
penguins.head()

,studyName,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
Sample Number,,,,,,,,,,,,,,,,
1,PAL0708,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
2,PAL0708,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
3,PAL0708,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
4,PAL0708,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
5,PAL0708,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN

In [9]:
abalone = pd.read_csv("../dx602-homework-09/abalone.tsv", sep="\t")
abalone.head()

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [4]:
dsg_material_df = pd.read_csv('../dx602-homework-09/design_materials_7.tsv', sep='\t')
material_cost_df = pd.read_csv('../dx602-homework-09/material_costs_7.tsv', sep='\t')

In [5]:
dsg_material_df

          design                    material  quantity_per_bed
0  4' x 4' x 18"                2" x 6" x 4'                20
1  4' x 4' x 18"  8" x 8" x 16" Cinder Block                12
2  4' x 8' x 18"                2" x 6" x 4'                 6
3  4' x 8' x 18"                2" x 6" x 8'                14
4  4' x 8' x 18"  8" x 8" x 16" Cinder Block                24
5  4' x 4' x 12"                2" x 6" x 4'                16
6  4' x 4' x 12"  8" x 8" x 16" Cinder Block                12
7  4' x 8' x 12"                2" x 6" x 4'                 2
8  4' x 8' x 12"                2" x 6" x 8'                12
9  4' x 8' x 12"  8" x 8" x 16" Cinder Block                24

In [6]:
material_cost_df

                     material  unit_cost
0                2" x 6" x 4'       5.92
1                2" x 6" x 8'       7.62
2  8" x 8" x 16" Cinder Block       3.53

In [11]:
penguins.groupby('Species').size()

Species
Adelie Penguin (Pygoscelis adeliae)          152
Chinstrap penguin (Pygoscelis antarctica)     68
Gentoo penguin (Pygoscelis papua)            124
dtype: int64

In [12]:
penguins.groupby('Species').size().reset_index(name='count')

                                     Species  count
0        Adelie Penguin (Pygoscelis adeliae)    152
1  Chinstrap penguin (Pygoscelis antarctica)     68
2          Gentoo penguin (Pygoscelis papua)    124

In [15]:
average_bill_length = penguins.groupby(['Species', 'Sex'])['Culmen Length (mm)'].mean()
average_bill_length

Species                                    Sex
Adelie Penguin (Pygoscelis adeliae)        FEMALE    37.257534
                                           MALE      40.390411
Chinstrap penguin (Pygoscelis antarctica)  FEMALE    46.573529
                                           MALE      51.094118
Gentoo penguin (Pygoscelis papua)          .         44.500000
                                           FEMALE    45.563793
                                           MALE      49.473770
Name: Culmen Length (mm), dtype: float64

In [20]:
avg = (penguins[penguins['Sex'] == 'FEMALE']
       .groupby('Species')['Culmen Length (mm)'].mean())
p11 = avg.idxmax()  # species name (string)
p11

'Chinstrap penguin (Pygoscelis antarctica)'

In [21]:
penguins.groupby("Individual ID").size().reset_index(name='count')

    Individual ID  count
0          N100A1      1
1          N100A2      1
2           N10A1      1
3           N10A2      1
4           N11A1      2
..            ...    ...
185         N98A2      1
186         N99A1      1
187         N99A2      1
188          N9A1      1
189          N9A2      1

[190 rows x 2 columns]